apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpddep
spec:
  selector:
    matchLabels:
      run: httpd
  replicas: 2
  template:
    metadata:
      labels:
        run: httpd
    spec:
      containers:
      - name: httpd
        image: dhruvin30/dhsoniweb:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: website 
  labels:
    run: httpd
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: httpd
  type: LoadBalancer
